DROP TABLE IF EXISTS  transactions;
CREATE TABLE transactions(
id INT UNSIGNED AUTO_INCREMENT  PRIMARY KEY NOT NULL,
user_id  INT UNSIGNED NULL,
product_id INT UNSIGNED NULL,
transaction_type VARCHAR(255),
count  INT NULL,
FOREIGN KEY (user_id) REFERENCES  users(id) ON DELETE CASCADE,
FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE  CASCADE
)ENGINE = InnoDB DEFAULT CHARSET = UTF8;